- name: play with variables
  hosts: local
  connection: local
  vars:
   COURSE: "DEVOPS WITH AWS"
   DURATION: "140 HRS"
   TRAINER: "SANTOSH"
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "course is: {{ COURSE }},trainer is: {{ TRAINER }}"