- name: datatypes
  hosts: local
  connection: local
  vars:
    PROGRAM: "DEVOPS WITH AWS"
    HRS: 140
    IS_LIVE: TRUE
    DETAILS:
     MONTH: 4
     TRAINER: SIVAKUMAR REDDY
    TOPICS:
   - LINUX
   - SHELL
   - ANSIBLE
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: |
      PROGRAM: {{ PROGRAM }}
      HRS: {{ HRS }}
      IS_LIVE: {{ IS_LIVE }}
      DETAILS: {{ DETAILS }}
      TPOICS: {{ TOPICS }}
      