- name: demo on datatypes
  hosts: local
  connection: local
  vars:
    PROGRAM: "DEVOPS WITH AWS"
    DURATION: 140
    IS_LIVE: TRUE
    DETAILS:
     MONTH: 4
     TRAINER: SANTOSH KUMAR
    TOPICS:
    - Linux
    - Shell
    - Ansible
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: |
      PROGRAM: {{ PROGRAM }}
      DURATION: {{ DURATION }}
      IS_LIVE: {{ IS_LIVE }}
      DETAILS: {{ DETAILS }}
      TPOICS: {{ TOPICS }}
      