[mongodb]
mongodb-dev.santoshdevops.online

[catalogue]
catalogue-dev.santoshdevops.online

[all:vars]
ansible_username=ec2_user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.santoshdevops.online