[mongodb]
mongodb-dev.santoshdevops.online

[redis]
redis-dev.santoshdevops.online

[user]
user-dev.santoshdevops.online

[cart]
cart-dev.santoshdevops.online

[catalogue]
catalogue-dev.santoshdevops.online

[mysql]
mysql-dev.santoshdevops.online

[Rabbitmq]
rabbitmq-dev.santoshdevops.online

[payment]
payment-dev.santoshdevops.yaml

[shipping]
shipping-devsantoshdevops.online


[all:vars]
ansible_username=ec2_user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.santoshdevops.online
CATALOGUE_HOST=catalogue-dev.santoshdevops.online
USER_HOST=user-dev.santoshdevops.online
CART_HOST=cart-dev.santoshdevops.online
REDIS_HOST=redis-dev.santoshdevps.online
