[mongodb]
mongodb-dev.santoshdevops.online

[redis]
redis-dev.santoshdevops.online

[user]
user-dev.santoshdevops.online

[cart]
cart-dev.santoshdevops.online

[catalogue]
catalogue-dev.santoshdevops.online

[mysql]
mysql-dev.santoshdevops.online

[rabbitmq]
rabbitmq-dev.santoshdevops.online

[payment]
payment-dev.santoshdevops.online

[shipping]
shipping-dev.santoshdevops.online

[frontend]
frontend-dev.santoshdevops.online

[all:vars]
ansible_username=ec2_user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.santoshdevops.online
CATALOGUE_HOST=catalogue-dev.santoshdevops.online
USER_HOST=user-dev.santoshdevops.online
CART_HOST=cart-dev.santoshdevops.online
REDIS_HOST=redis-dev.santoshdevps.online
SHIPPING_HOST=shipping-dev.santoshdevops.online
PAYMENT_HOST=payment-dev.santoshdevops.online
RABBITMQ_HOST=rabbit_mq-dev.santoshdevops.online
MYSQL_HOST=mysql-dev.santoshdevops.online